<a href="https://colab.research.google.com/github/ndb796/Natural-Language-Processing-Tutorial-for-KISA/blob/master/Numpy%20%EA%B8%B0%EB%B3%B8%20%EC%82%AC%EC%9A%A9%EB%B2%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h5><b>넘파이(Numpy)란?</b></h5>

* Numpy는 다차원 배열을 효과적으로 처리할 수 있도록 도와주는 도구입니다.
* 현실 세계의 다양한 데이터는 배열 형태로 표현할 수 있습니다.
* Python의 기본 List에 비해 빠르고 강력한 기능을 제공합니다.

<h5><b>List를 Numpy로 바꾸어 보기</b></h5>

In [0]:
import numpy as np

array = np.array([1, 2, 3])

print(array.size) # 배열의 크기
print(array.dtype) # 배열 원소의 타입
print(array[2]) # 인덱스 2의 원소

3
int64
3


<h5><b>Numpy 배열 초기화하기</b></h5>

In [0]:
import numpy as np

# 0부터 3까지의 배열 만들기
array1 = np.arange(4)
array2 = np.zeros((4, 4), dtype=float) # 0으로 초기화
array3 = np.ones((3, 3), dtype=str) # 1로 초기화

# 0부터 9까지 랜덤하게 초기화 된 배열 만들기
array4 = np.random.randint(0, 10, (3, 3))

# 평균이 0이고 표준편차가 1인 표준 정규를 띄는 배열
array5 = np.random.normal(0, 1, (3, 3))

print(array1)
print(array2)
print(array3)
print(array4)
print(array5)

[0 1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
[[1 7 9]
 [1 7 7]
 [8 1 8]]
[[-1.44796179 -1.28509791 -0.59567677]
 [ 0.74416933 -0.66555568 -0.61612865]
 [ 0.71287383  1.36797905  0.79253509]]


<h5><b>Numpy 배열 합치기</b></h5>

In [0]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.concatenate([array1, array2])

print(array3.shape)
print(array3)


(6,)
[1 2 3 4 5 6]


<h5><b>Numpy의 상수 연산</b></h5>

In [0]:
import numpy as np

array = np.random.randint(1, 10, size=4).reshape(2, 2)
result_array = array * 10
print(result_array)

[[70 60]
 [90 10]]


<h5><b>서로 다른 형태의 Numpy 객체 연산</b></h5>

In [0]:
import numpy as np

array1 = np.arange(4).reshape(2, 2)
array2 = np.arange(2)
array3 = array1 + array2

print(array3)

[[0 2]
 [2 4]]


<h5><b>Numpy의 집계 함수</b></h5>

In [0]:
import numpy as np

array = np.arange(16).reshape(4, 4)

print("최대값:", np.max(array))
print("최소값:", np.min(array))
print("합계:", np.sum(array))
print("평균값:", np.mean(array))

최대값: 15
최소값: 0
합계: 120
평균값: 7.5


<h5><b>Numpy 원소의 정렬</b></h5>

In [0]:
import numpy as np

# Numpy 원소 오름차순 정렬
array = np.array([5, 9, 10, 3, 1])
array.sort()
print(array)

# Numpy 원소 내림차순 정렬
array = np.array([5, 9, 10, 3, 1])
array.sort()
print(array[::-1])

# 각 열을 기준으로 정렬
array = np.array([[5, 9, 10, 3, 1], [8, 3, 4, 2, 5]])
array.sort(axis=0)
print(array)

[ 1  3  5  9 10]
[10  9  5  3  1]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]
